### PR TITLE
Enable check for metadata sheetname and is meta data sheet for arc template

### PR DESCRIPTION
**Pull request by Etschbeijer**
Closes Issue #453

### CODE REVIEW

**Comment by Etschbeijer** [comment]
> Hey, the Commit (and by this also PR message) could be a bit more concise. Especially `Template` is missing. But otherwise looks fine.
> 
> Also you should extend the logic to match that of ArcAssay and ArcStudy. Making use of the function you created. This way it would also transitively be tested.
> 
> EDIT: Just as @Freymaurer also mentioned

Should be fixed now

**Review by HLWeil — CHANGES_REQUESTED** [review]
Hey, usage of the newly added function in the "fromFsWorkbook" function is still missing. Line 277 including your changes

**Comment by Etschbeijer** [comment]
> Hey, usage of the newly added function in the "fromFsWorkbook" function is still missing. Line 277 including your changes

Do you mean in the tests?

**Comment by HLWeil** [comment]
No, I mean here:

image

**Review by HLWeil — APPROVED** [review]

**Pull request merged**
