### PR TITLE
Base spreadsheet parsers on string columns

### LINKED ISSUE #389: [Feature Request] Offer a string based parsing to ArcTable
**Is your feature request related to a problem? Please describe.**

In the near future we will start restoring Excel compatibility within Swate. Dues to the behavior of the Excel API using the standard FsSpreadsheet reader is not feasible, nor performant. 

**Describe the solution you'd like**

I would like to have an aPI level which works on string sequences, for example tableHeaders = `#seq<string>`, tableValues = `#seq<#seq<string>>`. Excel API should be able to work both column or row based, so no specific requirement there.

### PR DESCRIPTION
**Pull request by HLWeil**
closes #389

### CODE REVIEW

**Review by Freymaurer — COMMENTED** [review]
Lets say i have a sequence of header strings and a seq<seq<string>> for table-body-values. Which functions must i use to generate a ArcTable? Are these findable? Do they exist in this state?

**Comment by HLWeil** [comment]
```fsharp
open ARCtrl.Spreadsheet

let headerStringSeq : string seq = ...
let tableStringSeqs : string seq seq = ...

let transposedTable = 
    Seq.append [headerStringSeq] tableStringSeqs 
    |> Seq.transpose

let transposedTableList = 
    transposedTable 
    |> Seq.toList
    |> List.map (Seq.toList)


let arcTable = ArcTable.composeColumns transposedTableList
```

**Comment by Freymaurer** [comment]
> ```fsharp
> open ARCtrl.Spreadsheet
> 
> let headerStrings : string seq = ...
> let rowStringSeqs : string seq seq = ...
> 
> let columns = 
>     Seq.append [headerStrings] rowStringSeqs 
>     |> Seq.transpose
> 
> let columnsList = 
>     columns 
>     |> Seq.toList
>     |> List.map (Seq.toList)
> 
> 
> let arcTable = ArcTable.composeColumns columnsList 
> ```

love it!

**Review by Freymaurer — APPROVED** [review]

**Comment by Freymaurer** [comment]
Would be fine with it 👍

**Comment by HLWeil** [comment]
> ```fsharp
> open ARCtrl.Spreadsheet
> 
> let headerStrings : string seq = ...
> let rowStringSeqs : string seq seq = ...
> 
> let columns = 
>     Seq.append [headerStrings] rowStringSeqs 
>     |> Seq.transpose
> 
> let columnsList = 
>     columns 
>     |> Seq.toList
>     |> List.map (Seq.toList)
> 
> 
> let arcTable = ArcTable.composeColumns columnsList 
> ```

Now it's

```fsharp
open ARCtrl.Spreadsheet

let headerStrings : string seq = ...
let rowStringSeqs : string seq seq = ...

let columns = 
    Seq.append [headerStrings] rowStringSeqs 
    |> Seq.transpose

let columnsArray = 
    columns 
    |> Seq.toArray
    |> Array.map (Seq.toArray)

let arcTable = ArcTable.composeColumns columnsArray
```

**Review by Freymaurer — APPROVED** [review]

**Pull request merged**
