### PR TITLE
Developer copy

### LINKED ISSUE #156: [Feature Request] Use Paket or something similiar to keep common dependencies on same version
- Fable.Core
- FsSpreadsheet
We just found a leftover FsSpreadsheet dependency in ARCtrl.Contracts which lead to an strange error.

### LINKED ISSUE #158: [Feature Request] Copy member on person, etc.
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Freymaurer**
Closes #158
Closes #156

### CODE REVIEW

**Comment by Freymaurer** [comment]
Ups nearly requested merge on main :octocat:

**Comment by HLWeil** [comment]
Should we remove transpiled js files from git tracking?

**Review by HLWeil — COMMENTED** [review]
copy and paket changes look good! 
keeping all transpiled files seems a bit excessive. I mean this might even get worse with python and friends

**Comment by Freymaurer** [comment]
> Should we remove transpiled js files from git tracking?

Yes might be a good idea, will push the change

**Pull request merged**
