### PR TITLE
Speed boost for ArcTable creation and xlsx parsing

### PR DESCRIPTION
**Pull request by HLWeil**
Create, write and read study is now 12x faster. Ontology Annotations now have flat string as `Annotation Value`

### CODE REVIEW

**Review by Freymaurer — APPROVED** [review]
lgtm, but should be reworked to full sparse matrix as sson as tool stack is in stable release.

**Review by Freymaurer — CHANGES_REQUESTED** [review]
Only one change must be done: You forgot to make the performance test in ISA.Spreadsheet.Tests more strict, by decreasing the allowed runtime.

**Comment by HLWeil** [comment]
> lgtm, but should be reworked to full sparse matrix as sson as tool stack is in stable release.

Yeah, agreed. But when making the changes I noticed that there ARE indeed some decisions to be made so I postponed the rework.

**Comment by HLWeil** [comment]
I increased the strictness. But I think we might need some other method for this, as time elapsed is heavily dependent on the hardware. A quick search did not result in any better solution though.

**Review by Freymaurer — APPROVED** [review]

**Pull request merged**
