### PR TITLE
Added ARCtrl logos

### PR DESCRIPTION
**Pull request by HLWeil**
I propose this set consisting of 3 logos:
- square
- horizontal
- vertical

All other images are just assets for documentation and later potential fine-tuning.

Tell me what ~~you think~~ I want to hear.

@kMutagene 
@Freymaurer 
@Brilator 
@muehlhaus

### CODE REVIEW

**Comment by kMutagene** [comment]
*squeezes ARC* this bad boy can fit so many different kinds of research data in it

**Comment by HLWeil** [comment]
> _squeezes ARC_ this bad boy can fit so many different kinds of research data in it

Exactly 😆

**Comment by kMutagene** [comment]
@HLWeil note that we have a branding repo: https://github.com/nfdi4plants/Branding So i'd suggest putting this stuff there.

**Comment by HLWeil** [comment]
> @HLWeil note that we have a branding repo: https://github.com/nfdi4plants/Branding So i'd suggest putting this stuff there.

I'll link the logos in the README there

**Pull request merged**
