### PR TITLE
js-docs: replace auto-transpiled discriminate unions with helper functions

### PR DESCRIPTION
**Pull request by HLWeil**

### CODE REVIEW

**Comment by HLWeil** [comment]
@xiaoranzhou, what do you think about this syntax?

**Comment by xiaoranzhou** [comment]
> @xiaoranzhou, what do you think about this syntax?

Looks fine to me, thanks for asking :D

**Review by Freymaurer — CHANGES_REQUESTED** [review]
Please add some native js tests for example in: `tests/JavaScript/ISA.CompositeHeader`

**Comment by HLWeil** [comment]
Already done I think
https://github.com/nfdi4plants/ARCtrl/commit/4df81b99f97b1cf5a43d300fd66af11e0a531747

**Review by Freymaurer — APPROVED** [review]

**Comment by Freymaurer** [comment]
lgtm, ready to merge!

**Pull request merged**
